### ISSUE TITLE
Champion micro:bit

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#1]
Research possibilities of the micro:bit and share resources for workshops to use.

* [ ] Try out different exercises with students.
* [ ] Publish resources and results on the wiki.

**Comment by ablackman11** [comment]
Tried to contact Pr-kaspars....LOL!   Will try again!

**Comment by pablobm** [comment]
@pr-kaspars is taking some micro:bits home. @ablackman11 promises to help!
