### ISSUE TITLE
Prepare talk to give at meetups

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#10]

**Comment by ablackman11** [comment]
whats this for?

**Comment by pablobm** [comment]
Been meaning to do this for a while. I want to prepare 20-30 min talk to present at local meetups. This is to spread the work about WizzieWizzie and hopefully recruit new volunteers.

**Comment by pablobm** [comment]
Presenting this week at https://www.meetup.com/London-Emberjs-User-Group/events/260307336/

**Comment by pablobm** [comment]
Presented twice!
