### ISSUE TITLE
Sort power leads

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#13]
* Do we have all the leads we need?
* Do we need to mark them in some way to be better able to match power blocks with laptops?

**Comment by pablobm** [comment]
At NL, I have learned to tell most cables by just looking at them, but I know it's tricky and some people still have issues. What could help here?

**Comment by madebydavid** [comment]
At Rochelle we put coloured stickers on the laptops and matching ones on the power supplies. Seemed to save some time and prevent people accidentally plugging the wrong supply into the wrong laptop.

**Comment by madebydavid** [comment]
Let me know if you want the charity to order some coloured stickers to assist with this.

**Comment by pablobm** [comment]
Coloured stickers sounds great. Potential issue: more charger types than colours, but we can solve this by combining colours, using marker pens, or plain writing on the stickers.

**Comment by pablobm** [comment]
@madebydavid to buy stickers and @benzitohhh to... stick them.

**Comment by pablobm** [comment]
I have started sticking stickers on cables and laptops. Not sure how lasting the glue is though... let's check by the next retro.

**Comment by pablobm** [comment]
This is resolved!
