### ISSUE TITLE
Buy C6 ("Mickey Mouse") power cords for NL

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#14]
As described on this guide: https://community.fs.com/blog/small-power-cord-big-difference.html We are missing some at NL.

**Comment by madebydavid** [comment]
The charity can buy these - would you like me to order them and get them delivered to you?

**Comment by pablobm** [comment]
That would be great; we actually missed these very much last Friday. I think 3 is all is needed, but 5 may be best to provide replacements going forward.

**Comment by pablobm** [comment]
Best delivered to thoughtbot's offices in my name, I think (see https://thoughtbot.com/london). Or perhaps to the library?

**Comment by madebydavid** [comment]
@pablobm - do we need anything else for the North Library? Ordering 5 of these is below the £20 min for an order of "Add-On" items - thanks Bezos.

![image](https://user-images.githubusercontent.com/5401249/51267265-37f3a480-19b5-11e9-94fa-4b8c992428ed.png)

**Comment by pablobm** [comment]
Let me think about this and come back to you.

**Comment by pablobm** [comment]
@madebydavid, would ordering blue roll work? I've been meaning to buy some to help with spills etc that sometimes we get. They may also be useful in other locations?

**Comment by madebydavid** [comment]
I have ordered 6 of the cables and no blue roll because:

- I have 4 rolls of the blue roll in my garage and can deliver some to the library
- The blue roll comes in packs of 6 and thought that might be quite inconvenient
- The cables can be used elsewhere 

They should be delivered tomorrow to the Thoughtbot offices

**Comment by pablobm** [comment]
Received, thank you!
