### ISSUE TITLE
Shortcut to enable secondary VGA output

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#15]
When connecting laptops to big screens for show&tell, we have to go through a few menus and buttons to enable the correct output, each time we connect a laptop. It's a lot of faff.

Try find a shortcut for this, ideally autodetection, but if not at least a button that we can click just once.

**Comment by pablobm** [comment]
Yesterday I spent some time on this and got a prototype. Will test it in the following weeks.

**Comment by pablobm** [comment]
Actually, this is a first version of the script: https://github.com/pablobm/w2c3-livecd/blob/mirror-screen-shortcut/config/includes.chroot/usr/local/bin/mirror-screen.py

@madebydavid - Would you be able to try this out at WL and EL? If it works, I'll include it in the CD images with a desktop shortcut.

**Comment by madebydavid** [comment]
Nice! Will test it and let you know.

Performance wise - would it be bad if we ran this every 10 seconds so that we so that we don't need to remember to click the shortcut?

How does this compare to the `--auto` param for xrandr?
![image](https://user-images.githubusercontent.com/5401249/51476500-a05bd080-1d7d-11e9-8525-adb3039cfa7e.png)

**Comment by pablobm** [comment]
I didn't know of `--auto`. From reading that, I suspect that it doesn't mirror and scale, which my script does. I'll have a look just in case.

By "scale", I mean that the big screen shows exactly what the small screen is showing. In contrast,at NL we have a problem where the "mirror" mode more is more like a "overlap without changing dpi": the windows in the small screen maximize beyond where the small screen can hold, and students need to look at the big screen to be able to click on the sections that their small screen doesn't show. (Does that make sense?).

**Comment by pablobm** [comment]
Installed now on a few laptops at NL. Once we have a successful show&tell using this, I'll mark it as done.

**Comment by pablobm** [comment]
Confirmed working at NL.
