### ISSUE TITLE
Research Pibrella http://pibrella.com/

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#22]
Actions:
* [ ] Research available products.
* [ ] Research compatibility.
* [ ] Find products appropriate for our workshops and budget constraints.
* [ ] Decide whether to buy or not.
* [ ] Buy. Or not.

**Comment by pablobm** [comment]
@manuela-grindei Another one for you :-)

**Comment by manuela-grindei** [comment]
I will investigate Pibrella to see if it's a suitable choice for us. 
The official website I used so far is - http://pibrella.com/

**Comment by manuela-grindei** [comment]
I looked into this story and found that Pibrella can only work with Raspberry Pi, and is designed to facilitate Python coding in a fun way. Pibrella cannot be used with laptops like we have in our code clubs.
So unless we want to try Raspberry Pi and are ready to invest in it, we should not buy Pibrella.

**Comment by pablobm** [comment]
I think we can discard this then.
