### ISSUE TITLE
Create WiFi presets for all locations

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#25]
Every time we install a new laptop, we need to manually enter the location's WiFi credentials. On the other hand, at our locations WiFi credentials are not particularly secret. So why not just include them with our installer?

I have already done this for NL. See https://github.com/pablobm/w2c3-livecd/pull/10 (includes instructions). Let's do this for other locations too:

* [x] North Library
* [ ] Elizabeth House
* [ ] West Library

**Comment by pablobm** [comment]
@madebydavid @ablackman11: would you be able to provide the credentials file for EL and WL?

**Comment by madebydavid** [comment]
West Library:

- SSID: `Lib Public WiFi`
- Password: `get-reading`

Elizabeth House:

- SSID: `EH-Guest`
- Password: `ehguest2019`

**Comment by pablobm** [comment]
@madebydavid - Actually, it's a bit trickier than that. For the network manager to pick things up automatically, we need to provide their internal configuration file, which looks like this: https://github.com/pablobm/w2c3-livecd/pull/10/files

Having said that, I wonder if we could write something that figures out all that stuff from the SSID+password pairs. This is more effort, but would have two advantages:

1. It keeps working when the access points change at the location.
2. It's easier to maintain.

**Comment by madebydavid** [comment]
Ah, tricky - the library has a few different bssid values and Ubuntu does't seem to have saved the channel.

![image](https://user-images.githubusercontent.com/5401249/51476697-2f68e880-1d7e-11e9-99ff-c14d0e1347b9.png)

Is this saved to `/etc/wicd/wireless-settings.conf` can I grab that file from one of the library laptops and attach to this ticket?

**Comment by pablobm** [comment]
@madebydavid - That's right, just copy that file and paste it here. Before doing that, configure as many SSIDs as possible. It doesn't matter that they all have the same name/password, they count as different entries.

**Comment by pablobm** [comment]
Hm, maybe I should experiment with `wicd-cli` next Saturday: http://manpages.ubuntu.com/manpages/bionic/man8/wicd-cli.8.html

**Comment by madebydavid** [comment]
To exfiltrate the file easily (i have 2FA enabled on github and don't want to auth on the laptops there):

```bash
curl --form 'f:1=@/etc/wicd/wireless-settings.conf' ix.io
```
Then take a pic of the url returned
