### ISSUE TITLE
Contact parents re: rewards

### ISSUE THREAD

**Issue by pablobm** [WizzieWizzie/howto#28]
We want to offer inclusive rewards: not only chocolate. Ensure we have alternatives with no sugar, halal, without nuts, etc.

* [ ] @madebydavid to contact parents and seek approval and feedback.

**Comment by pablobm** [comment]
Changed this ticket to make the specific action point clearer.

**Comment by madebydavid** [comment]
Done - will update the other ticket #29 with feedback
